((magit-branch nil)
 (magit-commit nil)
 (magit-dispatch nil)
 (magit-fetch nil)
 (magit-gitignore nil)
 (magit-log
  ("-n256" "--graph" "--decorate")
  ("-n256" "--graph" "--color" "--decorate" "++header"))
 (magit-merge nil)
 (magit-pull nil)
 (magit-push nil)
 (magit-reset nil))
